[platformio]
core_dir = ./.pio

[env:megaatmega2560]

platform = atmelavr
board = megaatmega2560
framework = arduino

monitor_speed = 115200
monitor_filters = default, log2file

; build_unflags =
;     -std=gnu++14
; build_flags =
;     -std=gnu++17

