[platformio]
core_dir = ./.pio

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = espidf, arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps =
    fmtlib/fmt@^8.1.1

build_unflags =
    -std=gnu++11
build_flags =
    -std=c++2a
